<script setup>
const route = useRoute();

const { data, error } = await useAsyncData(`${route.params.id}-${route.params.episode}`, () => {
  return queryCollection("episodes").path(`/anime/${route.params.id}/episode/${route.params.episode.padStart(4, '0')}`).first();
});

if (!data.value) {
  throw createError({
    statusCode: 404,
    statusMessage: "Episode not found",
  });
}

function formatDate(dateString) {
  return new Date(dateString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

useSeoMeta({
  title: data.value?.title,
  description: data.value?.description,
  ogTitle: data.value?.title,
  ogDescription: data.value?.description,
});
</script>

<template>
  <div>
    <div v-if="error" class="text-center py-8">
      <p class="text-red-500">Episode not found</p>
      <NuxtLink
        to="/"
        class="text-blue-600 hover:text-blue-800 mt-4 inline-block"
      >
        ← Back to Home
      </NuxtLink>
    </div>

    <article v-else-if="data" class="max-w-4xl mx-auto">
      <!-- Breadcrumb -->
      <nav class="mb-6 text-sm text-gray-500">
        <NuxtLink to="/" class="hover:text-gray-700">Home</NuxtLink>
        <span class="mx-2">/</span>
        <NuxtLink to="/anime" class="hover:text-gray-700">Anime</NuxtLink>
        <span class="mx-2">/</span>
        <NuxtLink :to="data.path.split('/episode')[0]" class="hover:text-gray-700">
          {{ data.meta.animeTitle }}
        </NuxtLink>
        <span class="mx-2">/</span>
        <span class="hover:text-gray-700">Episode {{ data.meta.episodeDisplay }}</span>
      </nav>

      <!-- Episode Header -->
      <header class="mb-8">
        <h1 class="text-3xl font-bold mb-1">
          {{ data.meta.animeTitle }} Episode {{ data.meta.episodeDisplay }}, "{{
            data.title
          }}"
        </h1>

        <div class="text-gray-500 dark:text-gray-400">
          <span>{{ formatDate(data.airedDate) }}</span>
        </div>
      </header>

      <!-- Episode Content -->
      <div class="prose">
        <ContentRenderer :value="data" />
      </div>

      <div class="text-gray-500 dark:text-gray-400 italic mt-8">
        This article is generated by AI and may contain inaccuracies.
      </div>

      <!-- Navigation -->
      <footer class="mt-12 pt-6 border-t border-gray-200">
        <div class="flex justify-between items-center">
          <NuxtLink
            :to="data.path.split('/episode')[0]"
            class="inline-flex items-center text-blue-500 dark:text-blue-400 hover:text-blue-800 hover:dark:text-blue-600"
          >
            <UIcon name="lucide:chevron-left" class="mr-2" />
            Back to {{ data.meta.animeTitle }}
          </NuxtLink>

          <NuxtLink to="/" class="text-blue-500 dark:text-blue-400 hover:text-blue-800 hover:dark:text-blue-600">
            Home
          </NuxtLink>
        </div>
      </footer>
    </article>
  </div>
</template>
