<script setup>
const route = useRoute();

const { data, error } = await useAsyncData(
  `${route.params.id}-${route.params.episode}`,
  () => {
    return queryCollection("episodes")
      .path(
        `/anime/${route.params.id}/episode/${route.params.episode.padStart(4, "0")}`
      )
      .first();
  }
);

if (!data.value) {
  throw createError({
    statusCode: 404,
    statusMessage: "Episode not found",
  });
}

// Load previous/next episodes using Nuxt Content surround API (scoped to same anime)
const { data: surround } = await useAsyncData(
  `${route.params.id}-${route.params.episode}-surround`,
  async () => {
    const currentPath = `/anime/${route.params.id}/episode/${route.params.episode.padStart(4, "0")}`;
    const scope = `/anime/${route.params.id}/episode/%`;
    try {
      // Try using surround API, ordered by airedDate within the same anime
      const res = await queryCollection("episodes")
        .where("path", "LIKE", scope)
        .order("airedDate", "ASC")
        .surround(currentPath);
      const prev = Array.isArray(res) ? res?.[0] : (res?.before ?? null);
      const next = Array.isArray(res) ? res?.[1] : (res?.after ?? null);
      return { prev: prev ?? null, next: next ?? null };
    } catch {
      // Fallback using airedDate comparisons if surround isn't available
      const [prev, next] = await Promise.all([
        queryCollection("episodes")
          .where("path", "LIKE", scope)
          .where("airedDate", "<", data.value.airedDate)
          .order("airedDate", "DESC")
          .limit(1)
          .first(),
        queryCollection("episodes")
          .where("path", "LIKE", scope)
          .where("airedDate", ">", data.value.airedDate)
          .order("airedDate", "ASC")
          .limit(1)
          .first(),
      ]);
      return { prev: prev ?? null, next: next ?? null };
    }
  }
);

function formatDate(dateString) {
  return new Date(dateString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

useSeoMeta({
  title: data.value?.title,
  description: data.value?.description,
  ogTitle: data.value?.title,
  ogDescription: data.value?.description,
});

const breadcrumbs = computed(() => [
  { label: "Home", to: "/" },
  { label: "Anime", to: "/anime" },
  {
    label: data.value?.meta?.animeTitle ?? route.params.id,
    to: data.value?.path?.split("/episode")[0],
  },
  {
    label: `Episode ${data.value?.meta?.episodeDisplay ?? route.params.episode}`,
  },
]);
</script>

<template>
  <div>
    <div v-if="error" class="text-center py-8">
      <p class="text-red-500">Episode not found</p>
      <NuxtLink
        to="/"
        class="text-blue-600 hover:text-blue-800 mt-4 inline-block"
      >
        ← Back to Home
      </NuxtLink>
    </div>

    <article v-else-if="data" class="max-w-4xl mx-auto">
      <Breadcrumbs :items="breadcrumbs" />

      <!-- Episode Header -->
      <header class="mt-8">
        <h1 class="text-3xl font-bold mb-1">
          {{ data.meta.animeTitle }} Episode {{ data.meta.episodeDisplay }}, "{{
            data.title
          }}"
        </h1>
      </header>

      <div class="text-gray-500 dark:text-gray-400">
        {{ formatDate(data.airedDate) }}
      </div>
      <!-- Episode Content -->
      <div class="prose mt-8">
        <ContentRenderer :value="data" />
      </div>

      <div class="text-gray-500 dark:text-gray-400 italic mt-8">
        This article is generated by AI and may contain inaccuracies.
      </div>

      <!-- Prev/Next Navigation -->
      <footer
        v-if="surround && (surround.prev || surround.next)"
        class="mt-12 pt-6 border-t border-gray-200 dark:border-gray-700"
      >
        <div class="flex justify-between items-center">
          <NuxtLink
            v-if="surround.prev"
            :to="surround.prev.path"
            class="inline-flex items-center text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300"
          >
            <UIcon name="lucide:chevron-left" class="mr-2" />
            <span class="ml-1">
              Episode
              {{ surround.prev.meta?.episodeDisplay ?? surround.prev.episode }}
            </span>
          </NuxtLink>
          <span v-else />

          <NuxtLink
            v-if="surround.next"
            :to="surround.next.path"
            class="inline-flex items-center text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300"
          >
            <span class="mr-1">
              Episode
              {{ surround.next.meta?.episodeDisplay ?? surround.next.episode }}
            </span>
            <UIcon name="lucide:chevron-right" class="ml-2" />
          </NuxtLink>
        </div>
      </footer>
    </article>
  </div>
</template>
